OperationSpark/service-signups

README.md
greenlight.go
greenlight_test.go
mailgun.go
mailgun_test.go
server.go
server_test.go
signup.go
signup_test.go
slack.go
slack_test.go
zoom.go
zoom_test.go

Pass request context to downstream tasks so they're canceled if client cancels the initial request.
https://cloud.google.com/functions/docs/concepts/go-runtime#contextcontext
https://go.dev/blog/context

Pass request context though downstream tasks

---

.github/workflows/ci.yml
.github/workflows/deploy-testing.yml
README.md
errors.go
errors_test.go
greenlight.go
mailgun.go
shorty.go
signup.go
slack.go
twilio.go
zoom.go

Resolves #30 
Resolves #27
```
HTTP Error:
POST: https://api.zoom.us
/v2/meetings/8912345678/registrants?occurrence_id=1665594000000
Response:
429 Too Many Requests
{"code":429,"message":"You have exceeded the daily rate limit of (3) for Add meeting registrant API requests for the registrant (someone@domain.org). You can resume these API requests at GMT 00:00:00."}
```

Chore: Better Error Messaging, testing env CD workflow

---

.github/workflows/deploy-testing.yml
README.md
signup.go
signup_test.go

If an Info Session time does not have a corresponding Zoom Meeting ID, the registrants POST request was sent anyway:
```
problem signing user up: zoomService.run: HTTP Error:
POST: https://api.zoom.us
/v2/meetings/0/registrants?occurrence_id=1669046400000
Response:
404 Not Found
Meeting is not found or has expired.
Signup:
"Henri"
"Testaroni"
"[email redacted]"
"[cell redacted]"
"21 Nov 22 10:00 CST"
"TNhqqs226hAnDok72"
```
We have a guard to prevent sending the request if there was no meeting ID, but forgot to check the resulting `err`. This PR adds that check and returns before calling the Zoom API. 
```
problem signing user up: attachZoomMeetingID: no zoom meeting found with start hour: 10
Signup:
"Henri"
"Testaroni"
"[email redacted]"
"[cell redacted]"
"21 Nov 22 10:00 CST" …
```

Check attachZoomMeetingID error

---

.github/workflows/deploy-testing.yml
greenlight_test.go
signup.go

Partially resolves:
https://github.com/OperationSpark/service-signups/issues/35
- Add support for `UserLocation` string field.
- Send `userLocation` to Greenlight
- https://github.com/OperationSpark/greenlight-v2/pull/1135
- https://github.com/OperationSpark/operationspark-org-website-2022/pull/48

Support UserLocations

---

.github/workflows/deploy-testing.yml
README.md
zoom.go
zoom_test.go

Attempt to resolve the following error:
``` 
POST: https://api.zoom.us
/v2/meetings/[redacted]/registrants?occurrence_id=1673287200000
Response:
Signup:
401 Unauthorized
```
When a person signs up, the service authenticates with the Zoom API and receives an access token. I believe when multiple requests come in quick succession, the previous token is invalidated.
Ex:
```
clientA -> authenticate
token 12345 <- Zoom API
clientB -> authenticate
token 98876 <- Zoom API
token 12345 is no longer valid
```
The solution is to set the token in the global space and share the token state over subsequent invocations.
https://cloud.google.com/functions/docs/bestpractices/tips#use_global_variables_to_reuse_objects_in_future_invocations

Use global zoomCreds variable

---

.github/workflows/deploy-testing.yml
.github/workflows/deploy.yml
function.go
twilio.go

`opSparkRenderingSvcBaseUrl` will point to https://sms.operationspark.org

Add second env for rendering service base url 

---

.env.sample
.github/workflows/deploy-testing.yml
.github/workflows/deploy.yml
function.go
signup.go
signup_test.go
twilio.go

Since the renderer service was split from the Messenger service, it will remain the same across all environments. With this change, we can hardcode the Renderer Service API URL to cut down on confusion between the Renderer and Messenger URLs.

Hardcode SMS Renderer URL. Remove associated variables

---

.github/workflows/signup-smoke.yml
cmd/smoke/smoke_test.go
function.go
notify/info_session.go
notify/info_session_test.go
signup.go
signup_test.go

The main issue is that we're using the wrong env var here: 
https://github.com/OperationSpark/service-signups/pull/52/files#diff-323d89938d680c0b70940a4baf907cadf4c13e36f1bb20514a2a79cc2ff86eabR75
The Info Message URLs sent to students have the wrong host, `messenger.operationspark.org`, where it should be `sms.operationspark.org`.
Since splitting out the Operation Spark [Messenger](https://messenger.operationspark.org/conversations/0) app and the [Message Template Renderer](https://sms.operationspark.org/), using 'messaging' in variable names became too ambiguous. 
This PR hopes to be more specific with which app the variables are referring to.

Update rendering service types/vars

---

.github/workflows/deploy-staging.yml
.github/workflows/deploy-testing.yml
.github/workflows/deploy.yml

add `OS_RENDERING_SERVICE_URL` to the github workflow to match [fetched env](https://github.com/OperationSpark/service-signups/blob/main/function.go#L75)

add `OS_RENDERING_SERVICE_URL` to workflow

---

README.md
function.go
function_test.go

Resolves #54 
- Checks required environment variables are set when deployed
- If not, the server process will stop with an error code

Check for required env vars in GCP context

---

.gitignore
cmd/smoke/main.go
cmd/smoke/smoke_test.go
mailgun.go
mailgun_test.go
signup.go

Take the join code sent from the website sign up form and send it along with the other variables for the email template and message url so that students can join the class on greenlight
- send it along to the Renderer URL creator
- Ex: /m/eyJ0ZW1wbGF0ZSI...
- And a Greenlight link to join the session in the email template
- If no code present, omit the Join URL, from email and renderer URL

add join code to email template and message url

---

.github/workflows/golangci-lint.yml
notify/info_session.go
twilio.go

Add more context to these errors:
```
session-signups: One or more messages failed to send addNumberToConversation: createServiceConversationParticipant: Status: 400 - ApiError 50407: Invalid messaging binding address (null) More info: https://www.twilio.com/docs/errors/50407
```

Add identity value to error

---

README.md
signup.go
twilio.go

Update API to accept `smsOptIn` boolean field on SignUp JSON. 
- If `smsOptIn == false`, we don't send a text via Twilio
- else we send an opt-in confirmation followed up by the rest of the messages:
**Note**: Merging this will cause messages to stop sending if the [OS website PR](https://github.com/OperationSpark/operationspark-org-website-2022/pull/94) is not merged as the `smsOptIn` field will default to `false`.
We also need to ensure that the Twilio Messaging Service(s) used by this service is configured to listen for `"STOP"` messages.

Handle SMS opt-in data

---

cmd/smoke/smoke_test.go

Adds `"smsOptIn": true` to the SignUp POST JSON. 
The smoke tests were failing since SMS opt-in defaults to `false` and the SMS was never sent. Then we fetch the last message sent which happened to be from April.
https://github.com/OperationSpark/service-signups/actions/runs/5616235700/job/15236520915#step:4:64

Fix Smoke Test

---

.vscode/settings.json
README.md
cmd/smoke/main.go
cmd/smoke/smoke_test.go

Fixes broken smoke test after merging #68 
Continuation of #69 
Fetches the last two messages from Twilio API, expecting the first to be the opt-in confirmation.
Well, will fetch the last 2. Currently, it only fetches the last message because Twilio is blocking some number of messages until our A2P 10DLC Campaign is approved

Update Smoke test to support SMS opt-in

---

README.md
function.go
signup_test.go
snapmail.go

- Extract `SnapMail` client configuration out of `NewSnapMail` up to entry point (`function.go`)
- Update the SnapMail endpoint to `/events`

Move SnapMail Config to entrypoint

---

README.md
greenlight.go
mailgun.go
signup.go
signup_test.go
slack.go
snapmail.go
twilio.go

The signup should still work if a non-required task fails such as the slack message or snap mail tasks.
The register function failed if any of the tasks failed before.
Each task now has an isRequired method that will determine if the signup needs to fail if it is a required task.

optional tasks

---

.github/workflows/deploy-staging.yml
.github/workflows/deploy-testing.yml
.github/workflows/deploy.yml
README.md
reqsign.go
reqsign_test.go
signup_test.go
snapmail.go

The [SNAPmail service](https://github.com/OperationSpark/service-snapmail) now requires requests to be signed. We now use a SHA256 hex-encoded signature from the request body.

Sign SNAP mail requests

---

README.md
function.go

We're no longer using Google auth to close off the snapmail service since it needs to be public for Mailgun webhooks.
We're now depending on signed payloads

Remove google auth client

---

README.md
mailgun.go
mailgun_test.go
signup.go

Add variables for the updated Greenlight Auto-Enroll email template:
- `"greenlightEnrollUrl"`
- `"isGmail"`

Add auto-enroll variables for Mailgun template

---

README.md
signup.go

Fix Conversation->Signup linking
- **refactor: Improve context handling in SignupService's register method**
- **refactor: Swap parameters in Runner interface and update usage in runPostSignupTasks method**
- **feat: Skip post-signup tasks if SMS opt-in is not selected**

Fix Post-signup Tasks
